### ISSUE TITLE
Add a neutral state to the vote function and be able to remove a vote

### ISSUE THREAD

**Issue by deep-ink-ventures** [deep-ink-ventures/genesis-dao-node#35]
- add a neutral state to the vote, so we have an enum of `IN_FAVOR`, `AGAINST`, `NEUTRAL`

**Comment by deepink-mas** [comment]
I was thinking about the voting mechanism and thought perhaps we should extend/change the turnout_threshold into a minimum_majority, which would be the minimum number of votes by which the positive votes would have to exceed the negative votes in order for a proposal to be approved. This way, negative votes never have to wonder whether to vote or not, proposals that cannot attain even this minimum get rejected, and proposals whose majority is so tiny that it depends strongly on the phase of the moon, are rejected (and can be rerun). We also do not need a neutral vote if we go this way. In my mind this minimum_majority is something like 1% of tokens (but adjustable of course). This may also provide some protection against people trying to unduly influence voting results, since they have to have a minimum number of votes to approve a dubious proposal (maybe enough that we won't need check-pointing?)

**Comment by deep-ink-ventures** [comment]
@GHesericsu wdyt? It makes sense to me.

**Comment by GHesericsu** [comment]
Ya it makes sense to me too
