### ISSUE TITLE
Add the pallet_contract with ink! support to genesis dao

### ISSUE THREAD

**Issue by deep-ink-ventures** [deep-ink-ventures/genesis-dao-node#92]
1. Add [pallet_contracts](https://docs.rs/pallet-contracts/latest/pallet_contracts/) to our template. You can get inspiration from [the reference implementation](https://github.com/paritytech/substrate-contracts-node)
2. Once this is done, commit it to the staging branch and we deploy it
3. Deploy the [sample contract](https://use.ink/getting-started/setup)
4. Definition of done is that we can interact on https://contracts-ui.substrate.io/ with our node

**Comment by deepink-mas** [comment]
Currently stuck on step 3 because it won't let me click Next to instantiate the contract as described [here](https://use.ink/getting-started/deploy-your-contract#2-instantiate-a-contract-on-the-blockchain) (see image). Maybe something is missing from step 1, so looking at the reference implementation.

![image](https://user-images.githubusercontent.com/122525541/233039044-5c43b70e-cc35-41b6-95b4-00acb8547d0e.png)
